Change logic

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -56,13 +56,15 @@ jobs:
         if echo "$PR_BODY" | grep -q '\- \[ \]'; then
           echo "❌ Certaines cases ne sont pas cochées dans la checklist."
           exit 1
+        else
+          echo "✅ All required checkboxes are checked!"
         fi
           
-        EXPECTED_SHA=${{ github.event.pull_request.head.sha }}
-        if ! echo "$PR_BODY" | grep -q "$EXPECTED_SHA"; then
-          echo "❌ Le SHA dans la PR ne correspond pas au SHA actuel (${EXPECTED_SHA})."
-          exit 1
-        fi
+        # EXPECTED_SHA=${{ github.event.pull_request.head.sha }}
+        # if ! echo "$PR_BODY" | grep -q "$EXPECTED_SHA"; then
+        #   echo "❌ Le SHA dans la PR ne correspond pas au SHA actuel (${EXPECTED_SHA})."
+        #   exit 1
+        # fi
         echo "✅ Checklist validée : toutes les cases sont cochées et le SHA est correct."
 
 
