Change checker method

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -49,18 +49,27 @@ jobs:
     
     - name: Validate PR checkboxes
       id: checkboxes
-       
+      env:
+        GITHUB_TOKEN: ${{ secrets.TOCKEN_REGISTRY }}
       run: |
         # Get the PR body
-        PR_BODY=$(curl -s https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }})
-        echo $PR_BODY
-        CHECKLIST=$(echo "$PR_BODY" | jq -r '.body' | grep -q '\- \[ \]') #Look for unchecked boxes
-        if [ ! -z "$CHECKLIST" ]; then
-          echo "Error: Not all ❌ checklist items are completed."
+        
+        if grep -q '\- \[ \]' "$GITHUB_EVENT_PATH"; then
+          echo "❌ Certaines cases ne sont pas cochées dans la checklist."
           exit 1
         else
-          echo "✅ All required checkboxes are checked!"
+          echo "✅ Toutes les cases de la checklist sont cochées."
         fi
+
+        # PR_BODY=$(curl -s https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }})
+        # echo $PR_BODY
+        # CHECKLIST=$(echo "$PR_BODY" | jq -r '.body' | grep -P "^\s*- \[ \]") #Look for unchecked boxes
+        # if [ ! -z "$CHECKLIST" ]; then
+        #   echo "Error: Not all ❌ checklist items are completed."
+        #   exit 1
+        # else
+        #   echo "✅ All required checkboxes are checked!"
+        # fi
         
         # Define the required checkbox text
         # REQUIRED_CHECKBOXES=("Task 1" "Task 2")
