Change logic

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -52,13 +52,26 @@ jobs:
       env:
         GITHUB_TOKEN: ${{ secrets.TOCKEN_REGISTRY }}
       run: |
-       
-        if grep -q '\- \[ \]' "$GITHUB_EVENT_PATH"; then
-          echo "Error: Not all ❌ checklist items are completed."
+        PR_BODY=$(gh pr view ${{ github.event.pull_request.number }} --json body -q '.body')
+        if echo "$PR_BODY" | grep -q '\- \[ \]'; then
+          echo "❌ Certaines cases ne sont pas cochées dans la checklist."
           exit 1
-        else
-          echo "✅ All required checkboxes are checked!"
         fi
+          
+        EXPECTED_SHA=${{ github.event.pull_request.head.sha }}
+        if ! echo "$PR_BODY" | grep -q "$EXPECTED_SHA"; then
+          echo "❌ Le SHA dans la PR ne correspond pas au SHA actuel (${EXPECTED_SHA})."
+          exit 1
+        fi
+        echo "✅ Checklist validée : toutes les cases sont cochées et le SHA est correct."
+
+
+        # if grep -q '\- \[ \]' "$GITHUB_EVENT_PATH"; then
+        #   echo "Error: Not all ❌ checklist items are completed."
+        #   exit 1
+        # else
+        #   echo "✅ All required checkboxes are checked!"
+        # fi
 
         # PR_BODY=$(curl -s https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }})
         
@@ -69,8 +82,8 @@ jobs:
         # else
         #   echo "✅ All required checkboxes are checked!"
         # fi
-  
-        
+
+
         # Define the required checkbox text
         # REQUIRED_CHECKBOXES=("Task 1" "Task 2")
         # Check for each required checkbox
