Change checker method

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -52,22 +52,24 @@ jobs:
        
       run: |
         # Get the PR body
-        PR_BODY="${{ github.event.pull_request.body }}"
+        PR_BODY=$(curl -s https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }})
         echo $PR_BODY
-
-        # Define the required checkbox text
-        REQUIRED_CHECKBOXES=("Task 1" "Task 2")
-
-        Check for each required checkbox
-        for TASK in "${REQUIRED_CHECKBOXES[@]}"; do
-          if ! echo "$PR_BODY" | grep -qE "- \[x\] $TASK"; then
-            echo "❌ Checkbox for '$TASK' is not checked!"
-            exit 1
-          fi
-        done
-
+        CHECKLIST=$(echo "$PR_BODY" | jq -r '.body' | grep -P "^\s*- \[ \]") #Look for unchecked boxes
+        if [ ! -z "$CHECKLIST" ]; then
+          echo "Error: Not all ❌ checklist items are completed."
+          exit 1
+        fi
         echo "✅ All required checkboxes are checked!"
+        # Define the required checkbox text
+        # REQUIRED_CHECKBOXES=("Task 1" "Task 2")
 
+        # Check for each required checkbox
+        # for TASK in "${REQUIRED_CHECKBOXES[@]}"; do
+        #   if ! echo "$PR_BODY" | grep -qE "- \[x\] $TASK"; then
+        #     echo "❌ Checkbox for '$TASK' is not checked!"
+        #     exit 1
+        #   fi
+        # done
 
     - name: Cache node modules
       uses: actions/cache@v3
